### ISSUE TITLE
5000 占用

### ISSUE THREAD

**Issue by bottotl** [guangzhengli/ChatFiles#23]
第一次用 docker 求问，docker compose up 以后提示 5000 端口占用，修改端口 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/9837901/230765691-9bfc472e-2de1-4865-9ad0-47746b6f7862.png">
但是上传文件失败了
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/9837901/230765619-eec97083-2343-40b6-806f-e1013f0292ec.png">
请问这种情况要如何修改
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/9837901/230765722-431ef445-d282-4ecf-b977-21d365f2f33c.png">

**Comment by guangzhengli** [comment]
change docker-compose.yml chatfiles image ports 5000:5000 to 5000:5003

```yml
version: '2.2'
services:
  chatfiles:
    image: guangzhengli/chatfiles:test
    container_name: chatfiles
    ports:
      - 5000:5003 # change to 5000:5000 to 5000:5003
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  chatfiles-ui:
    image: guangzhengli/chatfiles-ui:test
    container_name: chatfiles-ui
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_FILES_SERVER_HOST=http://chatfiles:5000
    depends_on:
      - chatfiles
```
