### ISSUE TITLE
when i upload file, it tells me 'Error save file failed:, e0dd8b40-eaa4-47e7-8eb4-88d5caa483b3.'(run locally)

### ISSUE THREAD

**Issue by PuPuuu** [guangzhengli/ChatFiles#94]
<img width="511" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/78522811/c417b36b-0a80-40d4-991d-6f4457b180fe">

**Comment by PuPuuu** [comment]
<img width="656" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/78522811/d09e67b7-5ae9-4abe-a3da-1e0fcd0b581c">
<img width="1512" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/78522811/19d6030c-b05c-4a61-bb91-bda702a8ec59">
<img width="1512" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/78522811/cb0cf628-daac-452c-87ff-59a144194611">
<img width="1512" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/78522811/cebfa4fd-4abf-43f1-8f7f-6bf400f23da2">

**Comment by allentofight** [comment]
+1, the response is the following:

![image](https://github.com/guangzhengli/ChatFiles/assets/1235483/6e269b92-976d-479a-80be-7d90c381f2cd)

**Comment by allentofight** [comment]
local in Mac , change `public/uploads` to `/tmp` and it worked!

**Comment by PuPuuu** [comment]
> Your image leaked your OpenAI key!!! I have deleted your images. Please try uploading again and attach an accurate error message.

Thx, I have resolved this question by manually creating 'public/uploads' directory！
The reason is The program could not automatically create this directory, as for what caused it, I haven't read the code carefully, so I don't know the final reason

**Comment by PuPuuu** [comment]
but i still have problems:
<img width="547" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/78522811/11db8240-4d7a-4a25-b8e9-00cc4bcbc953">

**Comment by PuPuuu** [comment]
Is this error related to my proxy settings or the target url?

**Comment by PuPuuu** [comment]
this is the response:
![image](https://github.com/guangzhengli/ChatFiles/assets/78522811/c701909e-b77e-416d-adae-eda4d2cfe57e)

**Comment by ametzler1** [comment]
![image](https://github.com/guangzhengli/ChatFiles/assets/137511393/00a52145-a552-49f6-aff8-f12e7c94c9cb)
I seem to be having a similiar issue, also running local. 
For the life of me can't get the file to upload. 
Tried creating pulblic/uploads manually, but still no luck. 
Any suggestions on what I can try?

**Comment by learnerhouse** [comment]
> local in Mac , change `public/uploads` to `/tmp` and it worked!

I got the same error, and i fix `public/uploads` to `/tmp` , that not works, from the network error : '400' , that same like the network error, I change the open ai base url to another url , maybe that is the key to solve the error . here is the error slots
<img width="473" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/10653024/e1bd21a3-625c-49b4-9e32-b600cc2f0496">
<img width="595" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/10653024/792eff29-4ade-430d-9dae-732b7adab6a2">

**Comment by deltaLRD** [comment]
You can create a docker volume when deploy the project.
```yaml
version: '2.2'
services:
  chatfiles:
    image: guangzhengli/chatfiles:latest
    container_name: chatfiles
    ports:
      - 3000:3000
    environment:
      - OPENAI_TYPE=${OPENAI_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_DEPLOYMENT_NAME=${AZURE_OPENAI_API_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME=${AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_INSTANCE_NAME=${AZURE_OPENAI_API_INSTANCE_NAME}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads
      - NEXT_PUBLIC_CHAT_FILES_MAX_SIZE=0
    volumes:
      - ./files:/app/public/uploads
```
